<a href="https://colab.research.google.com/github/Arvind-tech98/Machine-Learning-algo.-examples/blob/main/KMeans_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-means clustering
> K-means clustering is a method of vector quantization that aims to partition n observations into k clusters in which each observation belongs to the cluster with the nearest mean (cluster centers or cluster centroid), serving as a prototype of the cluster.

> In other words, K-means clustering is an unsupervised machine learning algorithm that groups data points into k clusters based on their similarity or closeness between the data points.

 Here’s an example of k-means clustering using Python with scikit-learn library

In [ ]:
from sklearn.cluster import KMeans
import numpy as np

In [ ]:
# Generate a random dataset
x1 = 10 * np.random.rand(100, 2)
x1

array([[9.75885430e+00, 7.00619415e+00],
       [5.33129074e-02, 8.93459681e+00],
       [9.74559276e+00, 9.81485996e+00],
       [4.46074102e+00, 6.95567087e+00],
       [7.79714028e+00, 9.34666861e+00],
       [9.93343092e+00, 1.16398820e+00],
       [1.43772238e+00, 9.58145894e+00],
       [1.24164293e+00, 9.35245203e+00],
       [4.25961968e+00, 5.60550634e+00],
       [3.18464285e+00, 6.42357304e+00],
       [5.89922421e-01, 3.40262013e+00],
       [1.27032205e+00, 6.03664629e-01],
       [1.59967939e+00, 9.79410056e+00],
       [2.94838075e+00, 5.72078607e+00],
       [7.64292958e-01, 7.36824375e+00],
       [1.17621922e+00, 3.19385547e+00],
       [7.09008876e-01, 7.07664256e+00],
       [2.66684468e+00, 4.79580154e+00],
       [2.13564917e+00, 9.05161201e+00],
       [6.20268318e+00, 1.89109439e+00],
       [6.22509827e+00, 5.42575635e+00],
       [5.57214705e+00, 7.33821637e+00],
       [6.39601190e+00, 3.60103997e+00],
       [5.22681364e+00, 9.22604161e+00],
       [5.414943

In [ ]:
# Create a k-means model with 3 clusters
kmeans = KMeans(n_clusters=3, random_state=0,n_init="auto")

In [ ]:
# Fit the model to the data
kmeans.fit(x1)

KMeans(n_clusters=3, n_init='auto', random_state=0)

In [ ]:
# Get the cluster assignments for each data point
labels = kmeans.labels_
labels

array([0, 2, 0, 2, 0, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 0, 0,
       1, 0, 0, 0, 1, 2, 0, 1, 2, 1, 0, 0, 1, 0, 2, 2, 2, 1, 1, 1, 1, 2,
       0, 2, 0, 1, 2, 0, 2, 1, 0, 2, 0, 2, 0, 0, 2, 2, 2, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 2, 1, 0, 2, 1, 1, 2, 0, 0, 1, 2, 0, 2, 0, 1, 1,
       1, 0, 2, 1, 1, 1, 0, 1, 1, 0, 0, 2], dtype=int32)

In [ ]:
# Get the coordinates of the cluster centers
cluster_centers = kmeans.cluster_centers_
cluster_centers

array([[7.38389791, 7.39103908],
       [4.75188511, 2.50080593],
       [2.09225052, 7.48567091]])